// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.Data;

namespace Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210408191248_m1")]
    partial class m1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("ASPectLibrary.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "d206d232-33aa-495c-aa06-6262806d574f",
                            ConcurrencyStamp = "d206d232-33aa-495c-aa06-6262806d574f",
                            CreatedDate = new DateTime(2021, 4, 8, 12, 12, 47, 569, DateTimeKind.Local).AddTicks(8840),
                            Description = "This is the administrator role.",
                            Name = "Administrator",
                            NormalizedName = "Administrator"
                        },
                        new
                        {
                            Id = "7f82779e-5612-49c1-a107-65f05fa53b39",
                            ConcurrencyStamp = "7f82779e-5612-49c1-a107-65f05fa53b39",
                            CreatedDate = new DateTime(2021, 4, 8, 12, 12, 47, 575, DateTimeKind.Local).AddTicks(2420),
                            Description = "This is the instructor role.",
                            Name = "Instructor",
                            NormalizedName = "Instructor"
                        },
                        new
                        {
                            Id = "07f3d25d-29e5-41df-97d2-d39f49c33823",
                            ConcurrencyStamp = "07f3d25d-29e5-41df-97d2-d39f49c33823",
                            CreatedDate = new DateTime(2021, 4, 8, 12, 12, 47, 575, DateTimeKind.Local).AddTicks(2450),
                            Description = "This is the student role.",
                            Name = "Student",
                            NormalizedName = "Student"
                        });
                });

            modelBuilder.Entity("ASPectLibrary.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "5bb3f1ca-d27c-4655-b8d6-6c2b3016f2d3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4ab4cfe2-725f-402d-98af-cbe2004a7c84",
                            Email = "admin@aspect.com",
                            EmailConfirmed = true,
                            FirstName = "Adam",
                            LastName = "Aldridge",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ASPECT.COM",
                            NormalizedUserName = "ADMIN@ASPECT.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEIIpEI5fmbms2KcSJOaUzs7/RKTxq4IfJlP0fDps+652ypU5kApZ/6OFnohvm52v+Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "89e9fae2-ed9c-485c-bb66-09ac202e45bb",
                            TwoFactorEnabled = false,
                            UserName = "admin@aspect.com"
                        },
                        new
                        {
                            Id = "9216a976-f1ba-4d73-aff6-f818b4b5c6a7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6f4c0e5b-eb9e-455e-8b39-2cdce7f350cc",
                            Email = "instructor@aspect.com",
                            EmailConfirmed = true,
                            FirstName = "Ted",
                            LastName = "Smith",
                            LockoutEnabled = false,
                            NormalizedEmail = "INSTRUCTOR@ASPECT.COM",
                            NormalizedUserName = "INSTRUCTOR@ASPECT.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEPpiLSETHZXHW3oULnACtuL79eCAsS08tyGNCyrVf5biBQARy7t2Kl6dvURdHXbLhw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "21c712d8-0409-40f8-bdbd-2cbf2a6efdce",
                            TwoFactorEnabled = false,
                            UserName = "instructor@aspect.com"
                        },
                        new
                        {
                            Id = "363624a6-0978-4866-b5ee-b135a6fc3870",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e814c95d-79d4-4918-b96a-ede0aae343d0",
                            Email = "student@aspect.com",
                            EmailConfirmed = true,
                            FirstName = "Mike",
                            LastName = "Myers",
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT@ASPECT.COM",
                            NormalizedUserName = "STUDENT@ASPECT.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEKXSdEzIJE1c4Z1O5Si2hTGFJ8kTLGvnFfE8CwsVO9SfRXlnRC/dXBFBwJ1Y2sNbYA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0b562e96-796f-406b-bc7d-5ed46d0474a1",
                            TwoFactorEnabled = false,
                            UserName = "student@aspect.com"
                        });
                });

            modelBuilder.Entity("ASPectLibrary.Assignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignmentId1")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("courseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.HasKey("AssignmentId");

                    b.HasIndex("AssignmentId1");

                    b.HasIndex("courseId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("ASPectLibrary.Course", b =>
                {
                    b.Property<int>("courseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("courseID1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("courseTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("instructorID")
                        .HasColumnType("TEXT");

                    b.Property<string>("projectOutline")
                        .HasColumnType("TEXT");

                    b.Property<string>("term")
                        .HasColumnType("TEXT");

                    b.HasKey("courseID");

                    b.HasIndex("courseID1");

                    b.ToTable("Course");

                    b.HasData(
                        new
                        {
                            courseID = 1,
                            courseTitle = "COMP3800 - Practicum",
                            instructorID = "9216a976-f1ba-4d73-aff6-f818b4b5c6a7",
                            projectOutline = "https://www.bcit.ca/outlines/20211088135/",
                            term = "4"
                        },
                        new
                        {
                            courseID = 2,
                            courseTitle = "COMP4870 - Intranet Planning & Development",
                            instructorID = "9216a976-f1ba-4d73-aff6-f818b4b5c6a7",
                            projectOutline = "https://www.bcit.ca/outlines/20211049852/",
                            term = "4"
                        });
                });

            modelBuilder.Entity("ASPectLibrary.Membership", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Memberships");

                    b.HasData(
                        new
                        {
                            Id = "363624a6-0978-4866-b5ee-b135a6fc3870",
                            ProjectId = 1
                        },
                        new
                        {
                            Id = "363624a6-0978-4866-b5ee-b135a6fc3870",
                            ProjectId = 2
                        });
                });

            modelBuilder.Entity("ASPectLibrary.PeerEvaluation", b =>
                {
                    b.Property<int>("PeerEvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserBeingEvaluatedId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserEvaluatingId")
                        .HasColumnType("TEXT");

                    b.HasKey("PeerEvaluationId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserBeingEvaluatedId");

                    b.HasIndex("UserEvaluatingId");

                    b.ToTable("PeerEvaluations");
                });

            modelBuilder.Entity("ASPectLibrary.ProgressUpdate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Issues")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastWeekActivity")
                        .HasColumnType("TEXT");

                    b.Property<string>("NextWeekActivity")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProgressUpdates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2021, 4, 8, 12, 12, 47, 614, DateTimeKind.Local).AddTicks(5480),
                            Issues = "Schema may need to be reworked",
                            LastWeekActivity = "Finished DB Design",
                            NextWeekActivity = "Going to work on the API",
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2021, 4, 8, 12, 12, 47, 614, DateTimeKind.Local).AddTicks(7820),
                            Issues = "Need to find solution for deployment",
                            LastWeekActivity = "Finished API Design",
                            NextWeekActivity = "Going to implement the API",
                            ProjectId = 1
                        });
                });

            modelBuilder.Entity("ASPectLibrary.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppName")
                        .HasColumnType("TEXT");

                    b.Property<string>("AspNetUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamName")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId");

                    b.HasIndex("CourseId");

                    b.HasIndex("ProjectCategoryId");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            AppName = "Twitter",
                            AspNetUserId = "363624a6-0978-4866-b5ee-b135a6fc3870",
                            CourseId = 1,
                            Description = "An app for tweeting",
                            ProjectCategoryId = 1,
                            TeamName = "RA"
                        },
                        new
                        {
                            ProjectId = 2,
                            AppName = "PlaneGo",
                            AspNetUserId = "363624a6-0978-4866-b5ee-b135a6fc3870",
                            CourseId = 1,
                            Description = "It's like uber but for planes",
                            ProjectCategoryId = 2,
                            TeamName = "Team Fly"
                        });
                });

            modelBuilder.Entity("ASPectLibrary.ProjectCategory", b =>
                {
                    b.Property<int>("ProjectCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectCategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectCategoryId");

                    b.ToTable("ProjectCategory");

                    b.HasData(
                        new
                        {
                            ProjectCategoryId = 1,
                            ProjectCategoryName = "Blockchain"
                        },
                        new
                        {
                            ProjectCategoryId = 2,
                            ProjectCategoryName = "React"
                        });
                });

            modelBuilder.Entity("ASPectLibrary.ProjectRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Requirement")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.ToTable("ProjectRequirements");
                });

            modelBuilder.Entity("ASPectLibrary.ProjectRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProjectRoles");

                    b.HasData(
                        new
                        {
                            Id = "Arch",
                            RoleName = "Software Architect"
                        },
                        new
                        {
                            Id = "DBA",
                            RoleName = "Database Administrator"
                        },
                        new
                        {
                            Id = "UIUIX",
                            RoleName = "UI/UX Designer"
                        },
                        new
                        {
                            Id = "SD",
                            RoleName = "Software Developer"
                        },
                        new
                        {
                            Id = "PM",
                            RoleName = "Project Manager"
                        },
                        new
                        {
                            Id = "SA",
                            RoleName = "System Administrator"
                        },
                        new
                        {
                            Id = "FE",
                            RoleName = "Front End Developer"
                        },
                        new
                        {
                            Id = "BE",
                            RoleName = "Back End Developer"
                        },
                        new
                        {
                            Id = "QA",
                            RoleName = "Quality Assurance"
                        },
                        new
                        {
                            Id = "TE",
                            RoleName = "Software Tester"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "5bb3f1ca-d27c-4655-b8d6-6c2b3016f2d3",
                            RoleId = "d206d232-33aa-495c-aa06-6262806d574f"
                        },
                        new
                        {
                            UserId = "9216a976-f1ba-4d73-aff6-f818b4b5c6a7",
                            RoleId = "7f82779e-5612-49c1-a107-65f05fa53b39"
                        },
                        new
                        {
                            UserId = "363624a6-0978-4866-b5ee-b135a6fc3870",
                            RoleId = "07f3d25d-29e5-41df-97d2-d39f49c33823"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ASPectLibrary.Assignment", b =>
                {
                    b.HasOne("ASPectLibrary.Assignment", null)
                        .WithMany("Assignments")
                        .HasForeignKey("AssignmentId1");

                    b.HasOne("ASPectLibrary.Course", "Course")
                        .WithMany()
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("ASPectLibrary.Course", b =>
                {
                    b.HasOne("ASPectLibrary.Course", "course")
                        .WithMany()
                        .HasForeignKey("courseID1");

                    b.Navigation("course");
                });

            modelBuilder.Entity("ASPectLibrary.Membership", b =>
                {
                    b.HasOne("ASPectLibrary.ApplicationUser", "Student")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASPectLibrary.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ASPectLibrary.PeerEvaluation", b =>
                {
                    b.HasOne("ASPectLibrary.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASPectLibrary.ApplicationUser", "UserBeingEvaluated")
                        .WithMany()
                        .HasForeignKey("UserBeingEvaluatedId");

                    b.HasOne("ASPectLibrary.ApplicationUser", "UserEvaluating")
                        .WithMany()
                        .HasForeignKey("UserEvaluatingId");

                    b.Navigation("Project");

                    b.Navigation("UserBeingEvaluated");

                    b.Navigation("UserEvaluating");
                });

            modelBuilder.Entity("ASPectLibrary.ProgressUpdate", b =>
                {
                    b.HasOne("ASPectLibrary.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ASPectLibrary.Project", b =>
                {
                    b.HasOne("ASPectLibrary.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASPectLibrary.ProjectCategory", "ProjectCategory")
                        .WithMany()
                        .HasForeignKey("ProjectCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("ProjectCategory");
                });

            modelBuilder.Entity("ASPectLibrary.ProjectRequirement", b =>
                {
                    b.HasOne("ASPectLibrary.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("ASPectLibrary.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ASPectLibrary.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ASPectLibrary.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("ASPectLibrary.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASPectLibrary.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ASPectLibrary.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ASPectLibrary.Assignment", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
